/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gman.modeler.gui.components.services;

import java.awt.*;
import java.util.ArrayList;
import java.util.HashMap;

import com.gman.modeler.api.Queue;
import com.gman.modeler.api.RequestProcessor;
import com.gman.modeler.api.RequestType;
import com.gman.modeler.gui.api.DataCreator;
import com.gman.modeler.gui.api.DataMediator;
import com.gman.modeler.gui.components.util.RequestTypeTimerEditor;
import com.gman.modeler.services.BatchService;

/**
 * @author gman
 */
public class BatchServiceCreator extends DataCreator<BatchService> {

    /**
     * Creates new form BatchServiceCreator
     */
    public BatchServiceCreator(DataMediator mediator) {
        editor = new RequestTypeTimerEditor(mediator);
        initComponents();
        add(editor, BorderLayout.CENTER);
    }

    @Override
    public void reset() {
        nameTextField.setText("");
        editor.reset();
        batchSpinner.setValue(Integer.valueOf(1));
    }

    @Override
    public void parse(BatchService obj) {
        nameTextField.setText(obj.getName());
        editor.parse(obj);
        batchSpinner.setValue(Integer.valueOf(obj.getBatchSize()));
    }

    @Override
    public BatchService create() {
        return new BatchService(
                nameTextField.getText(),
                null,
                new ArrayList<Queue>(),
                editor.create(),
                new HashMap<RequestType, RequestProcessor>(),
                (Integer) batchSpinner.getValue());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        namePanel = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        batchPanel = new javax.swing.JPanel();
        batchLabel = new javax.swing.JLabel();
        batchSpinner = new javax.swing.JSpinner();

        setLayout(new java.awt.BorderLayout());

        namePanel.setLayout(new java.awt.GridLayout(1, 2));

        nameLabel.setText("Name");
        namePanel.add(nameLabel);
        namePanel.add(nameTextField);

        add(namePanel, java.awt.BorderLayout.PAGE_START);

        batchPanel.setLayout(new java.awt.GridLayout(1, 2));

        batchLabel.setText("Batch size");
        batchPanel.add(batchLabel);

        batchSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));
        batchPanel.add(batchSpinner);

        add(batchPanel, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private RequestTypeTimerEditor editor;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel batchLabel;
    private javax.swing.JPanel batchPanel;
    private javax.swing.JSpinner batchSpinner;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JPanel namePanel;
    private javax.swing.JTextField nameTextField;
    // End of variables declaration//GEN-END:variables
}
