package com.gman.modeler.gui.components;

import javax.swing.*;
import javax.swing.table.AbstractTableModel;
import java.awt.*;

import com.gman.modeler.api.Modeler;
import com.gman.modeler.api.Request;
import com.gman.modeler.gui.api.DataListener;

/**
 * @author gman
 */
public class RequestViewerComponent extends DataListener {

    private static final int INDEX_WIDTH = 50;
    private static final int TYPE_WIDTH = 100;
    private static final int EVENTS_WIDTH = 3000;

    private Modeler modeler;
    private final RequestViewerTableModel tableModel;

    /**
     * Creates new form RequestViewerComponent
     */
    public RequestViewerComponent() {
        tableModel = new RequestViewerTableModel();
        initComponents();
        requestTable.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        requestTable.getColumnModel().getColumn(0).setPreferredWidth(INDEX_WIDTH);
        requestTable.getColumnModel().getColumn(1).setPreferredWidth(TYPE_WIDTH);
        requestTable.getColumnModel().getColumn(2).setPreferredWidth(EVENTS_WIDTH);
    }

    @Override
    public void setModeler(Modeler modeler) {
        this.modeler = modeler;
        tableModel.update();
    }

    @Override
    public String getComponentName() {
        return "Request";
    }

    private class RequestViewerTableModel extends AbstractTableModel {

        public void update() {
            fireTableDataChanged();
        }

        @Override
        public int getColumnCount() {
            return 3;
        }

        @Override
        public int getRowCount() {
            return modeler != null ? modeler.getGeneratedRequests().size() : 0;
        }

        @Override
        public String getColumnName(int column) {
            switch (column) {
                case 0:
                    return "i";
                case 1:
                    return "type";
                case 2:
                    return "events";
                default:
                    return "";
            }
        }

        @Override
        public Object getValueAt(int rowIndex, int columnIndex) {
            final Request request = modeler.getGeneratedRequests().get(rowIndex);
            switch (columnIndex) {
                case 0:
                    return rowIndex;
                case 1:
                    return request.getType().getName();
                case 2:
                    return request.getEvents();
                default:
                    return "";
            }
        }
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        requestScrollPane = new JScrollPane();
        requestTable = new JTable();

        setLayout(new BorderLayout());

        requestTable.setModel(tableModel);
        requestScrollPane.setViewportView(requestTable);

        add(requestScrollPane, BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JScrollPane requestScrollPane;
    private JTable requestTable;
    // End of variables declaration//GEN-END:variables
}
