/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gman.modeler.gui.components.statistics;

import com.gman.modeler.gui.api.DataCreator;
import com.gman.modeler.statistics.ProcessedStatisticsAggregator;

/**
 * @author gman
 */
public class ProcessedStatisticsCreator extends DataCreator<ProcessedStatisticsAggregator> {

    /**
     * Creates new form ProcessedStatisticsCreator
     */
    public ProcessedStatisticsCreator() {
        initComponents();
    }

    @Override
    public ProcessedStatisticsAggregator create() {
        return new ProcessedStatisticsAggregator();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        optionsLabel = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        optionsLabel.setText("no options");
        add(optionsLabel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel optionsLabel;
    // End of variables declaration//GEN-END:variables
}
