package com.gman.modeler.gui;

import javax.swing.*;
import java.util.List;

import com.gman.modeler.gui.api.DataCreator;
import com.gman.modeler.gui.api.DataMediator;

/**
 * @author gman
 */
public class ComponentsFactory extends JDialog {

    private Object createdComponent;

    /**
     * Creates new form ComponentsFactory
     */
    public ComponentsFactory(MainForm parent) {
        super(parent, true);
        setResizable(false);
        initComponents();
    }

    public <T> T showDialogFor(Class<T> clazz, DataMediator mediator) {
        return showDialogFor(clazz, mediator, null);
    }

    public <T> T showDialogFor(Class<T> clazz, DataMediator mediator, T obj) {
        typesTabbedPane.removeAll();
        final List<DataCreator> dataCreators = mediator.getCreatorsFor(clazz);
        if (dataCreators != null) {
            for (final DataCreator creator : dataCreators) {
                typesTabbedPane.addTab(creator.getCreatorName(), creator);
                if (obj != null && obj.getClass().equals(creator.createClass())) {
                    creator.parse(obj);
                    typesTabbedPane.setSelectedComponent(creator);
                } else {
                    creator.reset();
                }
            }
        }
        pack();
        setVisible(true);
        //suspend hear until setVisible(false) call
        return (T) createdComponent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        typesTabbedPane = new javax.swing.JTabbedPane();
        cancelButton = new javax.swing.JButton();
        okButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(okButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cancelButton))
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(typesTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(typesTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(cancelButton)
                                        .addComponent(okButton)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        createdComponent = ((DataCreator) typesTabbedPane.getSelectedComponent()).create();
        setVisible(false);
        dispose();
    }//GEN-LAST:event_okButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        createdComponent = null;
        setVisible(false);
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton okButton;
    private javax.swing.JTabbedPane typesTabbedPane;
    // End of variables declaration//GEN-END:variables
}
