package com.gman.modeler.gui.components.queueselectors;

import com.gman.modeler.gui.api.DataCreator;
import com.gman.modeler.queues.selectors.ShortestQueueSelector;

/**
 * @author gman
 */
public class ShortestQueueSelectorCreator extends DataCreator<ShortestQueueSelector> {

    /**
     * Creates new form ShortestQueueSelector
     */
    public ShortestQueueSelectorCreator() {
        initComponents();
    }

    @Override
    public ShortestQueueSelector create() {
        return new ShortestQueueSelector();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        optionsLabel = new javax.swing.JLabel();

        setLayout(new java.awt.GridLayout(1, 1));

        optionsLabel.setText("No options");
        add(optionsLabel);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel optionsLabel;
    // End of variables declaration//GEN-END:variables
}
