package com.gman.modeler.gui.components.timers;

import com.gman.modeler.gui.api.DataCreator;
import com.gman.modeler.timer.ConstantTimer;

/**
 * @author gman
 */
public class ConstantTimerCreator extends DataCreator<ConstantTimer> {

    /**
     * Creates new form ConstantTimerCreator
     */
    public ConstantTimerCreator() {
        initComponents();
    }

    @Override
    public void reset() {
        valueTextField.setText("");
    }

    @Override
    public void parse(ConstantTimer obj) {
        valueTextField.setText(Double.toString(obj.getInterval()));
    }

    @Override
    public ConstantTimer create() {
        try {
            final double interval = Double.parseDouble(valueTextField.getText());
            return new ConstantTimer(interval);
        } catch (NumberFormatException e) {
            return null;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        timerLabel = new javax.swing.JLabel();
        valueTextField = new javax.swing.JTextField();

        setLayout(new java.awt.GridLayout(1, 2));

        timerLabel.setText("Interval");
        add(timerLabel);

        valueTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valueTextFieldActionPerformed(evt);
            }
        });
        add(valueTextField);
    }// </editor-fold>//GEN-END:initComponents

    private void valueTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valueTextFieldActionPerformed
        try {
            Double.parseDouble(valueTextField.getText());
        } catch (NumberFormatException e) {
            valueTextField.setText("1.0");
        }
    }//GEN-LAST:event_valueTextFieldActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel timerLabel;
    private javax.swing.JTextField valueTextField;
    // End of variables declaration//GEN-END:variables
}
