/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gman.modeler.gui.components.timers;

import com.gman.modeler.gui.api.DataCreator;
import com.gman.modeler.timer.ExponentialDistributionTimer;

/**
 *
 * @author gman
 */
public class ExponentialDistributionTimerCreator extends DataCreator<ExponentialDistributionTimer> {

    /**
     * Creates new form ExponentialDistributionTimerCreator
     */
    public ExponentialDistributionTimerCreator() {
        initComponents();
    }
    
    @Override
    public void reset() {
        lamdaTextField.setText("");
    }

    @Override
    public void parse(ExponentialDistributionTimer obj) {
        lamdaTextField.setText(Double.toString(obj.getLamda()));
    }

    @Override
    public ExponentialDistributionTimer create() {
        try {
            final double lamda = Double.parseDouble(lamdaTextField.getText());
            return new ExponentialDistributionTimer(lamda);
        } catch (NumberFormatException e) {
            return null;
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lamdaLabel = new javax.swing.JLabel();
        lamdaTextField = new javax.swing.JTextField();

        setLayout(new java.awt.GridLayout(1, 2));

        lamdaLabel.setText("Lamda");
        add(lamdaLabel);
        add(lamdaTextField);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lamdaLabel;
    private javax.swing.JTextField lamdaTextField;
    // End of variables declaration//GEN-END:variables
}
